const starterListings=[
{title:"Noise-canceling headphones",price:48,category:"Tech",city:"2 miles away",emoji:"🎧",color:"#e8e1ff"},{title:"Healthy monstera plant",price:22,category:"Home",city:"1 mile away",emoji:"🪴",color:"#e3f4d5"},{title:"Classic 35mm camera",price:95,category:"Hobbies",city:"4 miles away",emoji:"📷",color:"#f5e4ce"},{title:"Everyday canvas sneakers",price:35,category:"Style",city:"3 miles away",emoji:"👟",color:"#dcecff"},{title:"Compact turntable",price:80,category:"Tech",city:"5 miles away",emoji:"🎵",color:"#f6ddeb"},{title:"Ceramic table lamp",price:30,category:"Home",city:"2 miles away",emoji:"💡",color:"#fff1c7"},{title:"Weekend travel bag",price:42,category:"Style",city:"6 miles away",emoji:"👜",color:"#e5ddda"},{title:"Complete skateboard",price:55,category:"Hobbies",city:"1 mile away",emoji:"🛹",color:"#dff4f1"}];
const config=window.FLIPORA_CONFIG;
const db=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey);
let listings=[...starterListings],currentUser=null,activeCategory="All",authMode="signin";
const grid=document.querySelector("#listingGrid"),emptyState=document.querySelector("#emptyState"),searchInput=document.querySelector("#searchInput"),sellDialog=document.querySelector("#sellDialog"),authDialog=document.querySelector("#authDialog"),accountDialog=document.querySelector("#accountDialog");

const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const categoryEmoji=category=>({Tech:"💻",Home:"🏠",Style:"👕",Hobbies:"🎨",Other:"✨"})[category]||"✨";
const safeImageUrl=value=>{try{const url=new URL(value,location.origin);return url.protocol==="https:"||url.protocol==="http:"?url.href:""}catch{return""}};
function renderListings(){const query=searchInput.value.trim().toLowerCase();const visible=listings.filter(item=>(activeCategory==="All"||item.category===activeCategory)&&item.title.toLowerCase().includes(query));grid.innerHTML=visible.map(item=>{const imageUrl=safeImageUrl(item.image_url);return `<article class="listing-card"><div class="listing-image" style="--card-bg:${item.color||"#e8e1ff"}">${imageUrl?`<img src="${escapeHtml(imageUrl)}" alt="${escapeHtml(item.title)}" loading="lazy">`:item.emoji||"✨"}</div><div class="listing-body"><div class="listing-meta"><span class="listing-category">${escapeHtml(item.category)}</span><span class="price">$${Number(item.price).toLocaleString()}</span></div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.city||"Local pickup")}</p>${item.id?`<button class="buy-button" data-buy="${item.id}">Buy securely</button>`:"<span class=\"sample-note\">Sample listing</span>"}</div></article>`}).join("");emptyState.hidden=visible.length!==0}
async function loadListings(){const{data,error}=await db.from("listings").select("id,title,price,category,city,image_url,condition,created_at,seller_id").eq("status","active").order("created_at",{ascending:false});listings=!error&&data?.length?[...data.map(item=>({...item,emoji:categoryEmoji(item.category),color:"#e8e1ff"})),...starterListings]:[...starterListings];renderListings()}
document.querySelector("#categoryFilters").addEventListener("click",event=>{const button=event.target.closest("[data-category]");if(!button)return;activeCategory=button.dataset.category;document.querySelectorAll(".chip").forEach(chip=>chip.classList.toggle("active",chip===button));renderListings()});searchInput.addEventListener("input",renderListings);

function setAuthMode(mode){authMode=mode;const signup=mode==="signup";document.querySelector("#authEyebrow").textContent=signup?"Join the community":"Welcome back";document.querySelector("#authTitle").textContent=signup?"Create your Flipora account":"Sign in to Flipora";document.querySelector("#authSubmit").textContent=signup?"Create account":"Sign in";document.querySelector("#authSwitch").textContent=signup?"Already have an account? Sign in":"New here? Create an account";document.querySelector("#displayNameLabel").hidden=!signup;document.querySelector("#forgotPassword").hidden=signup;document.querySelector("#authMessage").textContent="";document.querySelector("#authForm").elements.password.autocomplete=signup?"new-password":"current-password"}
function openAuth(mode){setAuthMode(mode);if(!authDialog.open)authDialog.showModal()}
document.querySelector("#signInButton").addEventListener("click",()=>openAuth("signin"));document.querySelector("#createAccountButton").addEventListener("click",()=>openAuth("signup"));document.querySelector("#authSwitch").addEventListener("click",()=>setAuthMode(authMode==="signin"?"signup":"signin"));document.querySelector("[data-close-auth]").addEventListener("click",()=>authDialog.close());document.querySelector("[data-close-account]").addEventListener("click",()=>accountDialog.close());document.querySelector("#accountButton").addEventListener("click",()=>accountDialog.showModal());
document.querySelector("#authForm").addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget),email=String(form.get("email")).trim(),password=String(form.get("password")),message=document.querySelector("#authMessage"),submit=document.querySelector("#authSubmit");submit.disabled=true;submit.textContent="Please wait…";message.textContent="";const result=authMode==="signup"?await db.auth.signUp({email,password,options:{data:{display_name:String(form.get("displayName")||"").trim()},emailRedirectTo:`${location.origin}/`}}):await db.auth.signInWithPassword({email,password});submit.disabled=false;setAuthMode(authMode);if(result.error){message.textContent=result.error.message;return}if(authMode==="signup"&&!result.data.session){message.textContent="Check your email to verify your account, then sign in.";event.currentTarget.reset();return}authDialog.close();event.currentTarget.reset();showToast(authMode==="signup"?"Welcome to Flipora!":"Signed in successfully")});
document.querySelector("#forgotPassword").addEventListener("click",async()=>{const email=document.querySelector("#authForm").elements.email.value.trim(),message=document.querySelector("#authMessage");if(!email){message.textContent="Enter your email first.";return}const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/`});message.textContent=error?error.message:"Password reset email sent."});
document.querySelector("#signOutButton").addEventListener("click",async()=>{await db.auth.signOut();accountDialog.close();showToast("You are signed out")});
async function paymentRequest(path,options={}){const{data}=await db.auth.getSession();if(!data.session)throw new Error("Sign in required");const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session.access_token}`,...(options.headers||{})}});const body=await response.json();if(!response.ok)throw new Error(body.error||"Payment request failed");return body}
document.querySelector("#connectStripeButton").addEventListener("click",async()=>{const button=document.querySelector("#connectStripeButton");button.disabled=true;button.textContent="Opening Stripe…";try{const result=await paymentRequest("/.netlify/functions/connect-onboard",{method:"POST"});location.href=result.url}catch(error){showToast(error.message);button.disabled=false;button.textContent="Connect Stripe"}});
grid.addEventListener("click",async event=>{const button=event.target.closest("[data-buy]");if(!button)return;if(!currentUser){openAuth("signin");document.querySelector("#authMessage").textContent="Sign in to purchase this item.";return}button.disabled=true;button.textContent="Opening checkout…";try{const result=await paymentRequest("/.netlify/functions/create-checkout",{method:"POST",body:JSON.stringify({listingId:button.dataset.buy})});location.href=result.url}catch(error){showToast(error.message);button.disabled=false;button.textContent="Buy securely"}});
document.querySelectorAll("[data-open-sell]").forEach(button=>button.addEventListener("click",()=>{if(!currentUser){openAuth("signup");document.querySelector("#authMessage").textContent="Create an account or sign in to sell.";return}if(accountDialog.open)accountDialog.close();sellDialog.showModal()}));
const photoInput=document.querySelector("#photoInput"),photoPreview=document.querySelector("#photoPreview");
photoInput.addEventListener("change",()=>{const files=[...photoInput.files].slice(0,5);if(photoInput.files.length>5){photoInput.value="";photoPreview.innerHTML="<p>Please choose no more than 5 photos.</p>";return}photoPreview.innerHTML=files.length?files.map(file=>`<img src="${URL.createObjectURL(file)}" alt="Selected item photo preview">`).join(""):"<p>Tap above to take photos or choose them from your gallery.</p>"});
async function uploadListingPhoto(file,userId){if(!file)return null;if(file.size>8*1024*1024)throw new Error("Each photo must be smaller than 8 MB.");const extension=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`${userId}/${crypto.randomUUID()}.${extension}`;const{error}=await db.storage.from("listing-images").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw error;return db.storage.from("listing-images").getPublicUrl(path).data.publicUrl}
document.querySelector("#sellForm").addEventListener("submit",async event=>{event.preventDefault();if(!currentUser)return openAuth("signin");const submit=event.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent="Uploading…";try{const form=new FormData(event.currentTarget),photos=[...photoInput.files].slice(0,5);if(!photos.length)throw new Error("Add at least one item photo.");const imageUrl=await uploadListingPhoto(photos[0],currentUser.id);const listing={seller_id:currentUser.id,title:String(form.get("title")).trim(),price:Number(form.get("price")),category:String(form.get("category")),condition:String(form.get("condition")),city:String(form.get("city")).trim(),description:String(form.get("description")||"").trim(),image_url:imageUrl};const{error}=await db.from("listings").insert(listing);if(error)throw error;event.currentTarget.reset();photoPreview.innerHTML="<p>Tap above to take photos or choose them from your gallery.</p>";sellDialog.close();await loadListings();await updateAccount(currentUser);showToast("Your listing is live!")}catch(error){showToast(error.message)}finally{submit.disabled=false;submit.textContent="Publish listing"}});
async function updateAccount(user){currentUser=user;const signedIn=Boolean(user);document.querySelector("#signInButton").hidden=signedIn;document.querySelector("#createAccountButton").hidden=signedIn;document.querySelector("#accountButton").hidden=!signedIn;if(!user)return;const name=user.user_metadata?.display_name||user.email.split("@")[0];document.querySelector("#accountName").textContent=name;document.querySelector("#accountInitial").textContent=name.charAt(0).toUpperCase();document.querySelector("#profileName").textContent=name;document.querySelector("#profileEmail").textContent=user.email;const{count}=await db.from("listings").select("id",{count:"exact",head:true}).eq("seller_id",user.id);document.querySelector("#listingCount").textContent=count||0;try{const status=await paymentRequest("/.netlify/functions/connect-status");document.querySelector("#payoutStatus").textContent=status.connected?"Ready to receive payments":status.detailsSubmitted?"Verification pending":"Not connected";document.querySelector("#connectStripeButton").textContent=status.connected?"Manage payout setup":"Connect Stripe"}catch{document.querySelector("#payoutStatus").textContent="Setup required"}}
db.auth.onAuthStateChange((_event,session)=>updateAccount(session?.user||null));db.auth.getSession().then(({data})=>updateAccount(data.session?.user||null));
function showToast(message){const toast=document.querySelector("#toast");toast.textContent=message;toast.classList.add("show");window.setTimeout(()=>toast.classList.remove("show"),3000)}
const pageStatus=new URLSearchParams(location.search);if(pageStatus.get("payment")==="success")showToast("Payment completed. Your order is confirmed!");if(pageStatus.get("payment")==="cancelled")showToast("Checkout cancelled. No payment was taken.");if(pageStatus.get("stripe")==="return")showToast("Stripe onboarding received. Checking your payout status.");
document.querySelector("#year").textContent=new Date().getFullYear();loadListings();

