const starterListings=[
{title:"Noise-canceling headphones",price:48,category:"Tech",city:"Macon, GA",emoji:"🎧",color:"#e8e1ff"},{title:"Healthy monstera plant",price:22,category:"Home",city:"Atlanta, GA",emoji:"🪴",color:"#e3f4d5"},{title:"Classic 35mm camera",price:95,category:"Hobbies",city:"Savannah, GA",emoji:"📷",color:"#f5e4ce"},{title:"Everyday canvas sneakers",price:35,category:"Style",city:"Augusta, GA",emoji:"👟",color:"#dcecff"},{title:"Compact turntable",price:80,category:"Tech",city:"Columbus, GA",emoji:"🎵",color:"#f6ddeb"},{title:"Ceramic table lamp",price:30,category:"Home",city:"Athens, GA",emoji:"💡",color:"#fff1c7"},{title:"Weekend travel bag",price:42,category:"Style",city:"Warner Robins, GA",emoji:"👜",color:"#e5ddda"},{title:"Complete skateboard",price:55,category:"Hobbies",city:"Valdosta, GA",emoji:"🛹",color:"#dff4f1"}];
const config=window.FLIPORA_CONFIG;
const db=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey);
let listings=[...starterListings],currentUser=null,activeCategory="All",authMode="signin",membershipActive=false;
const grid=document.querySelector("#listingGrid"),emptyState=document.querySelector("#emptyState"),searchInput=document.querySelector("#searchInput"),sellDialog=document.querySelector("#sellDialog"),authDialog=document.querySelector("#authDialog"),accountDialog=document.querySelector("#accountDialog");
const authForm=document.querySelector("#authForm"),passwordResetForm=document.querySelector("#passwordResetForm"),passwordResetMessage=document.querySelector("#passwordResetMessage");
let passwordRecoveryMode=location.hash.includes("type=recovery");

const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const categoryEmoji=category=>({Tech:"💻",Home:"🏠",Style:"👕",Hobbies:"🎨",Vehicles:"🚗","Lawn & Garden":"🌿",Tools:"🛠️","Heavy Equipment":"🚜",Hauling:"🚚",Jobs:"💼",Events:"🎟️","Business Services":"💻",Other:"✨"})[category]||"✨";
const safeImageUrl=value=>{try{const url=new URL(value,location.origin);return url.protocol==="https:"||url.protocol==="http:"?url.href:""}catch{return""}};
const mapsDirectionsUrl=locationText=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(String(locationText||""))}`;
function renderListings(){const query=searchInput.value.trim().toLowerCase();const visible=listings.filter(item=>(activeCategory==="All"||item.category===activeCategory)&&item.title.toLowerCase().includes(query));grid.innerHTML=visible.map(item=>{const imageUrl=safeImageUrl(item.image_url),place=item.city||"Local pickup",key=item.id||`sample-${starterListings.indexOf(item)}`;return `<article class="listing-card" data-listing-key="${escapeHtml(key)}" tabindex="0" aria-label="Open ${escapeHtml(item.title)} details"><div class="listing-image" style="--card-bg:${item.color||"#e8e1ff"}">${imageUrl?`<img src="${escapeHtml(imageUrl)}" alt="${escapeHtml(item.title)}" loading="lazy">`:item.emoji||"✨"}</div><div class="listing-body"><div class="listing-meta"><span class="listing-category">${escapeHtml(item.category)}</span><span class="price">$${Number(item.price).toLocaleString()}</span></div><h3>${escapeHtml(item.title)}</h3><p class="listing-location">📍 ${escapeHtml(place)}</p><a class="directions-link listing-directions" href="${escapeHtml(mapsDirectionsUrl(place))}" target="_blank" rel="noopener">Get directions</a>${item.id?`<button class="buy-button" data-buy="${item.id}">Buy securely</button>`:"<span class=\"sample-note\">Sample listing · Tap for details</span>"}</div></article>`}).join("");emptyState.hidden=visible.length!==0}
async function loadListings(){let response=await db.from("listings").select("id,title,price,category,city,image_url,image_urls,video_url,description,condition,created_at,seller_id").eq("status","active").order("created_at",{ascending:false});if(response.error&&String(response.error.message||"").includes("image_urls"))response=await db.from("listings").select("id,title,price,category,city,image_url,description,condition,created_at,seller_id").eq("status","active").order("created_at",{ascending:false});const{data,error}=response;listings=!error&&data?.length?[...data.map(item=>({...item,emoji:categoryEmoji(item.category),color:"#e8e1ff"})),...starterListings]:[...starterListings];renderListings()}
document.querySelector("#categoryFilters").addEventListener("click",event=>{const button=event.target.closest("[data-category]");if(!button)return;activeCategory=button.dataset.category;document.querySelectorAll(".chip").forEach(chip=>chip.classList.toggle("active",chip===button));renderListings()});searchInput.addEventListener("input",renderListings);

function setAuthMode(mode){authMode=mode;const signup=mode==="signup";document.querySelector("#authEyebrow").textContent=signup?"Join the community":"Welcome back";document.querySelector("#authTitle").textContent=signup?"Create your Flipora account":"Sign in to Flipora";document.querySelector("#authSubmit").textContent=signup?"Create account":"Sign in";document.querySelector("#authSwitch").textContent=signup?"Already have an account? Sign in":"New here? Create an account";document.querySelector("#displayNameLabel").hidden=!signup;document.querySelector("#forgotPassword").hidden=signup;document.querySelector("#authMessage").textContent="";document.querySelector("#authForm").elements.password.autocomplete=signup?"new-password":"current-password"}
function openAuth(mode){passwordRecoveryMode=false;passwordResetForm.hidden=true;authForm.hidden=false;setAuthMode(mode);if(!authDialog.open)authDialog.showModal()}
function showPasswordRecovery(){passwordRecoveryMode=true;if(accountDialog.open)accountDialog.close();authForm.hidden=true;passwordResetForm.hidden=false;passwordResetMessage.textContent="";if(!authDialog.open)authDialog.showModal()}
document.querySelector("#signInButton").addEventListener("click",()=>openAuth("signin"));document.querySelector("#createAccountButton").addEventListener("click",()=>openAuth("signup"));document.querySelector("#authSwitch").addEventListener("click",()=>setAuthMode(authMode==="signin"?"signup":"signin"));document.querySelector("[data-close-auth]").addEventListener("click",()=>authDialog.close());document.querySelector("#closePasswordReset").addEventListener("click",()=>{passwordRecoveryMode=false;passwordResetForm.hidden=true;authForm.hidden=false;authDialog.close()});document.querySelector("[data-close-account]").addEventListener("click",()=>accountDialog.close());document.querySelector("#accountButton").addEventListener("click",()=>accountDialog.showModal());
document.querySelector("#authForm").addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget),email=String(form.get("email")).trim(),password=String(form.get("password")),message=document.querySelector("#authMessage"),submit=document.querySelector("#authSubmit");submit.disabled=true;submit.textContent="Please wait…";message.textContent="";const result=authMode==="signup"?await db.auth.signUp({email,password,options:{data:{display_name:String(form.get("displayName")||"").trim()},emailRedirectTo:`${location.origin}/`}}):await db.auth.signInWithPassword({email,password});submit.disabled=false;setAuthMode(authMode);if(result.error){message.textContent=result.error.message;return}if(authMode==="signup"&&!result.data.session){message.textContent="Check your email to verify your account, then sign in.";event.currentTarget.reset();return}authDialog.close();event.currentTarget.reset();showToast(authMode==="signup"?"Welcome to Flipora!":"Signed in successfully")});
document.querySelector("#forgotPassword").addEventListener("click",async()=>{const email=document.querySelector("#authForm").elements.email.value.trim(),message=document.querySelector("#authMessage");if(!email){message.textContent="Enter your email first.";return}const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/`});message.textContent=error?error.message:"Password reset email sent."});
passwordResetForm.addEventListener("submit",async event=>{event.preventDefault();passwordResetMessage.textContent="";const form=new FormData(event.currentTarget),password=String(form.get("newPassword")||""),confirmation=String(form.get("confirmPassword")||"");if(password.length<8){passwordResetMessage.textContent="Use at least 8 characters.";return}if(password!==confirmation){passwordResetMessage.textContent="The passwords do not match.";return}const button=event.currentTarget.querySelector('[type="submit"]');button.disabled=true;button.textContent="Saving…";try{const{error}=await db.auth.updateUser({password});if(error)throw error;passwordRecoveryMode=false;history.replaceState({},document.title,location.pathname);event.currentTarget.reset();passwordResetForm.hidden=true;authForm.hidden=false;authDialog.close();showToast("Password updated successfully")}catch(error){passwordResetMessage.textContent=error.message}finally{button.disabled=false;button.textContent="Save new password"}});
document.querySelector("#changeMemberPassword").addEventListener("click",showPasswordRecovery);
document.querySelector("#signOutButton").addEventListener("click",async()=>{await db.auth.signOut();accountDialog.close();showToast("You are signed out")});
document.querySelector("#switchBuyerAccountButton").addEventListener("click",async()=>{const button=document.querySelector("#switchBuyerAccountButton");button.disabled=true;button.textContent="Switching…";await db.auth.signOut();accountDialog.close();openAuth("signin");document.querySelector("#authEyebrow").textContent="Buyer account";document.querySelector("#authTitle").textContent="Sign in as a buyer";document.querySelector("#authMessage").textContent="Use a different email from the seller account that listed the item.";button.disabled=false;button.textContent="Switch buyer account"});
const sellerLocationInput=document.querySelector("#sellerLocationInput"),profileDirectionsLink=document.querySelector("#profileDirectionsLink");
function showProfileLocation(value){sellerLocationInput.value=value||"";profileDirectionsLink.hidden=!value;if(value)profileDirectionsLink.href=mapsDirectionsUrl(value)}
document.querySelector("#saveSellerLocation").addEventListener("click",async()=>{if(!currentUser)return;const locationValue=sellerLocationInput.value.trim();if(!locationValue){showToast("Enter a city, ZIP code, or public meetup location.");return}const button=document.querySelector("#saveSellerLocation");button.disabled=true;button.textContent="Saving…";const{data,error}=await db.auth.updateUser({data:{seller_location:locationValue}});button.disabled=false;button.textContent="Save";if(error)return showToast(error.message);currentUser=data.user;showProfileLocation(locationValue);document.querySelector('#sellForm input[name="city"]').value=locationValue;showToast("Seller location saved.")});
async function paymentRequest(path,options={}){const{data}=await db.auth.getSession();if(!data.session)throw new Error("Sign in required");const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session.access_token}`,...(options.headers||{})}});const body=await response.json();if(!response.ok)throw new Error(body.error||"Payment request failed");return body}
async function startMembershipCheckout(button){if(!currentUser){openAuth("signup");document.querySelector("#authMessage").textContent="Create an account or sign in to become a seller member.";return}button.disabled=true;const originalText=button.textContent;button.textContent="Opening checkout…";try{const result=await paymentRequest("/.netlify/functions/create-membership-checkout",{method:"POST",body:"{}"});location.href=result.url}catch(error){showToast(error.message);button.disabled=false;button.textContent=originalText}}
document.querySelectorAll(".membership-checkout-button").forEach(button=>button.addEventListener("click",()=>startMembershipCheckout(button)));
document.querySelector("#connectStripeButton").addEventListener("click",async()=>{const button=document.querySelector("#connectStripeButton");if(!membershipActive)return startMembershipCheckout(button);button.disabled=true;button.textContent="Opening Stripe…";try{const result=await paymentRequest("/.netlify/functions/connect-onboard",{method:"POST"});location.href=result.url}catch(error){showToast(error.message);button.disabled=false;button.textContent="Connect Stripe"}});
async function buyListing(button,listingId){if(!currentUser){openAuth("signin");document.querySelector("#authMessage").textContent="Sign in with a buyer account to purchase this item. Buyers do not need a membership.";return}button.disabled=true;button.textContent="Opening checkout…";try{const result=await paymentRequest("/.netlify/functions/create-checkout",{method:"POST",body:JSON.stringify({listingId})});if(!result?.url)throw new Error("Stripe checkout did not return a payment link");location.assign(result.url)}catch(error){const message=String(error?.message||"Checkout is unavailable");showToast(message);button.disabled=false;button.title=message;if(message.includes("own listing"))button.textContent="Use a different buyer account";else if(message.includes("membership")||message.includes("payout"))button.textContent="Seller payment setup incomplete";else button.textContent="Try checkout again";window.setTimeout(()=>{if(button.isConnected&&!button.disabled){button.textContent="Buy securely";button.removeAttribute("title")}},6000)}}
const listingDialog=document.querySelector("#listingDialog"),galleryMain=document.querySelector("#listingGalleryMain"),galleryThumbs=document.querySelector("#listingThumbnails"),detailBuyButton=document.querySelector("#detailBuyButton");
function listingFromKey(key){return key.startsWith("sample-")?starterListings[Number(key.slice(7))]:listings.find(item=>String(item.id)===key)}
function listingMedia(item){const gallery=Array.isArray(item.image_urls)?item.image_urls:[];return [...new Set([item.image_url,...gallery,item.video_url].map(safeImageUrl).filter(Boolean))]}
function isVideoUrl(url){try{return /\.(mp4|webm|mov|m4v|3gp)$/i.test(new URL(url).pathname)}catch{return false}}
function showGalleryMedia(url,title){galleryMain.innerHTML=url?(isVideoUrl(url)?`<video src="${escapeHtml(url)}" controls playsinline preload="metadata" aria-label="Video of ${escapeHtml(title)}"></video>`:`<img src="${escapeHtml(url)}" alt="${escapeHtml(title)}">`):`<span aria-hidden="true">${itemEmojiForTitle(title)}</span>`;galleryThumbs.querySelectorAll("button").forEach(button=>button.classList.toggle("active",button.dataset.media===url))}
function itemEmojiForTitle(title){return listings.find(item=>item.title===title)?.emoji||"✨"}
function openListingDetails(item){if(!item)return;const media=listingMedia(item),place=item.city||"Local pickup";document.querySelector("#detailCategory").textContent=item.category||"Other";document.querySelector("#detailPrice").textContent=`$${Number(item.price).toLocaleString()}`;document.querySelector("#detailTitle").textContent=item.title;document.querySelector("#detailCondition").textContent=item.condition?`Condition: ${item.condition}`:"";document.querySelector("#detailDescription").textContent=item.description||"Contact the seller for more details about this item.";document.querySelector("#detailLocation").textContent=`📍 ${place}`;document.querySelector("#detailDirections").href=mapsDirectionsUrl(place);galleryThumbs.innerHTML=media.length>1?media.map((url,index)=>`<button class="listing-thumbnail${index===0?" active":""}" type="button" data-media="${escapeHtml(url)}" aria-label="${isVideoUrl(url)?"Play item video":`View photo ${index+1}`}">${isVideoUrl(url)?'<span class="video-thumb-icon" aria-hidden="true">▶</span>':`<img src="${escapeHtml(url)}" alt="">`}</button>`).join(""):"";showGalleryMedia(media[0]||"",item.title);detailBuyButton.hidden=!item.id;detailBuyButton.dataset.buy=item.id||"";detailBuyButton.disabled=false;detailBuyButton.textContent="Buy securely";const messageSellerButton=document.querySelector("#detailMessageSellerButton");messageSellerButton.hidden=!item.id||!item.seller_id;messageSellerButton.dataset.listingId=item.id||"";messageSellerButton.dataset.sellerId=item.seller_id||"";messageSellerButton.dataset.listingTitle=item.title||"this item";const sellerProfileLink=document.querySelector("#detailSellerProfileLink");sellerProfileLink.hidden=!item.seller_id;sellerProfileLink.href=item.seller_id?`/reviews.html?seller=${encodeURIComponent(item.seller_id)}`:"/reviews.html";document.querySelector("#detailSampleNote").hidden=Boolean(item.id);listingDialog.showModal()}
grid.addEventListener("click",event=>{const button=event.target.closest("[data-buy]");if(button){event.stopPropagation();buyListing(button,button.dataset.buy);return}if(event.target.closest("a"))return;const card=event.target.closest("[data-listing-key]");if(card)openListingDetails(listingFromKey(card.dataset.listingKey))});
grid.addEventListener("keydown",event=>{if((event.key==="Enter"||event.key===" ")&&!event.target.closest("button,a")){event.preventDefault();const card=event.target.closest("[data-listing-key]");if(card)openListingDetails(listingFromKey(card.dataset.listingKey))}});
galleryThumbs.addEventListener("click",event=>{const button=event.target.closest("[data-media]");if(button)showGalleryMedia(button.dataset.media,document.querySelector("#detailTitle").textContent)});detailBuyButton.addEventListener("click",()=>buyListing(detailBuyButton,detailBuyButton.dataset.buy));document.querySelector("[data-close-listing]").addEventListener("click",()=>listingDialog.close());
document.querySelectorAll("[data-open-sell]").forEach(button=>button.addEventListener("click",()=>{if(!currentUser){openAuth("signup");document.querySelector("#authMessage").textContent="Create an account or sign in to sell.";return}if(accountDialog.open)accountDialog.close();sellDialog.showModal()}));
document.querySelectorAll("[data-start-category]").forEach(button=>button.addEventListener("click",()=>{if(!currentUser){openAuth("signup");document.querySelector("#authMessage").textContent="Create an account or sign in to post this opportunity.";return}document.querySelector('#sellForm select[name="category"]').value=button.dataset.startCategory;sellDialog.showModal()}));
const photoInput=document.querySelector("#photoInput"),cameraInput=document.querySelector("#cameraInput"),photoPreview=document.querySelector("#photoPreview"),videoInput=document.querySelector("#videoInput"),videoPreview=document.querySelector("#videoPreview");
let listingPhotoFiles=[],listingVideoFile=null,listingVideoPreviewUrl="";
let listingPhotoPreviewUrls=[];
const selectedPhotoFiles=()=>listingPhotoFiles.slice(0,6);
function addListingPhotos(fileList){const incoming=[...fileList].filter(file=>['image/jpeg','image/png','image/webp'].includes(file.type));const remaining=6-listingPhotoFiles.length;if(!remaining)return showToast("You already selected the maximum of 6 photos.");listingPhotoFiles.push(...incoming.slice(0,remaining));if(incoming.length>remaining)showToast("Only the first 6 photos were added.");renderPhotoPreview()}
function renderPhotoPreview(){listingPhotoPreviewUrls.forEach(url=>URL.revokeObjectURL(url));listingPhotoPreviewUrls=[];const files=selectedPhotoFiles();photoPreview.innerHTML=files.length?`${files.map((file,index)=>{const url=URL.createObjectURL(file);listingPhotoPreviewUrls.push(url);return `<figure class="selected-photo"><img src="${url}" alt="Selected item photo ${index+1}"><button type="button" data-remove-photo="${index}" aria-label="Remove photo ${index+1}">×</button></figure>`}).join("")}<p class="photo-count">${files.length} of 6 photos selected</p>`:"<p>Take a new photo or choose up to 6 from your gallery or files.</p>"}
document.querySelector("#takePhotoButton").addEventListener("click",()=>cameraInput.click());document.querySelector("#choosePhotoButton").addEventListener("click",()=>photoInput.click());
cameraInput.addEventListener("change",()=>{addListingPhotos(cameraInput.files);cameraInput.value=""});photoInput.addEventListener("change",()=>{addListingPhotos(photoInput.files);photoInput.value=""});photoPreview.addEventListener("click",event=>{const button=event.target.closest("[data-remove-photo]");if(!button)return;listingPhotoFiles.splice(Number(button.dataset.removePhoto),1);renderPhotoPreview()});
function clearListingVideo(){if(listingVideoPreviewUrl)URL.revokeObjectURL(listingVideoPreviewUrl);listingVideoPreviewUrl="";listingVideoFile=null;videoInput.value="";videoPreview.innerHTML="<p>Add one short video so buyers can see the item in action.</p>"}
function videoDuration(file){return new Promise((resolve,reject)=>{const element=document.createElement("video"),url=URL.createObjectURL(file);element.preload="metadata";element.onloadedmetadata=()=>{URL.revokeObjectURL(url);resolve(element.duration)};element.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("This video could not be opened."))};element.src=url})}
async function selectListingVideo(file){if(!file)return;if(!["video/mp4","video/webm","video/quicktime","video/x-m4v","video/3gpp"].includes(file.type))return showToast("Choose an MP4, WebM, MOV, M4V, or phone video.");if(file.size>25*1024*1024)return showToast("Video must be smaller than 25 MB.");try{const duration=await videoDuration(file);if(!Number.isFinite(duration)||duration>30.5)return showToast("Video must be 30 seconds or shorter.");clearListingVideo();listingVideoFile=file;listingVideoPreviewUrl=URL.createObjectURL(file);videoPreview.innerHTML=`<video src="${listingVideoPreviewUrl}" controls playsinline preload="metadata"></video><button type="button" data-remove-video>Remove video</button><p>${Math.ceil(duration)} seconds · ready to upload</p>`}catch(error){showToast(error.message)}}
videoInput.addEventListener("change",async()=>{await selectListingVideo(videoInput.files[0]);if(!listingVideoFile)videoInput.value=""});videoPreview.addEventListener("click",event=>{if(event.target.closest("[data-remove-video]"))clearListingVideo()});
async function uploadListingPhoto(file,userId){if(!file)return null;if(file.size>8*1024*1024)throw new Error("Each photo must be smaller than 8 MB.");const extension=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`${userId}/${crypto.randomUUID()}.${extension}`;const{error}=await db.storage.from("listing-images").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw error;return db.storage.from("listing-images").getPublicUrl(path).data.publicUrl}
async function uploadListingVideo(file,userId){if(!file)return null;if(file.size>25*1024*1024)throw new Error("Video must be smaller than 25 MB.");const extension=(file.name.split(".").pop()||"mp4").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`${userId}/${crypto.randomUUID()}.${extension}`;const bucket=db.storage.from("listing-videos");const{error}=await bucket.upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw new Error(`Video upload failed: ${error.message}`);return bucket.getPublicUrl(path).data.publicUrl}
document.querySelector("#sellForm").addEventListener("submit",async event=>{event.preventDefault();if(!currentUser)return openAuth("signin");const submit=event.currentTarget.querySelector('[type="submit"]');submit.disabled=true;submit.textContent="Uploading…";try{const form=new FormData(event.currentTarget),photos=selectedPhotoFiles();if(!photos.length)throw new Error("Take a photo or choose one from your files.");const imageUrls=[];for(const photo of photos)imageUrls.push(await uploadListingPhoto(photo,currentUser.id));let videoUrl=null;if(listingVideoFile){submit.textContent="Uploading video…";videoUrl=await uploadListingVideo(listingVideoFile,currentUser.id)}const listing={seller_id:currentUser.id,status:"active",title:String(form.get("title")).trim(),price:Number(form.get("price")),category:String(form.get("category")),condition:String(form.get("condition")),city:String(form.get("city")).trim(),description:String(form.get("description")||"").trim(),image_url:imageUrls[0],image_urls:imageUrls,video_url:videoUrl};let{error}=await db.from("listings").insert(listing);if(error&&String(error.message||"").includes("image_urls")){delete listing.image_urls;({error}=await db.from("listings").insert(listing))}if(error)throw error;event.currentTarget.reset();cameraInput.value="";photoInput.value="";listingPhotoFiles=[];renderPhotoPreview();clearListingVideo();sellDialog.close();await loadListings();await updateAccount(currentUser);showToast("Your listing is live on the front page!")}catch(error){showToast(error.message)}finally{submit.disabled=false;submit.textContent="Publish listing"}});
async function updateAccount(user){currentUser=user;const signedIn=Boolean(user);document.querySelector("#signInButton").hidden=signedIn;document.querySelector("#createAccountButton").hidden=signedIn;document.querySelector("#accountButton").hidden=!signedIn;document.querySelector("#adminAccessButton").hidden=String(user?.email||"").toLowerCase()!=="romarevgreen@gmail.com";if(!user){membershipActive=false;showProfileLocation("");return}const name=user.user_metadata?.display_name||user.email.split("@")[0],sellerLocation=user.user_metadata?.seller_location||"";document.querySelector("#accountName").textContent=name;document.querySelector("#accountInitial").textContent=name.charAt(0).toUpperCase();document.querySelector("#profileName").textContent=name;document.querySelector("#profileEmail").textContent=user.email;showProfileLocation(sellerLocation);const cityInput=document.querySelector('#sellForm input[name="city"]');if(sellerLocation&&!cityInput.value)cityInput.value=sellerLocation;const{count}=await db.from("listings").select("id",{count:"exact",head:true}).eq("seller_id",user.id).eq("status","active");const sellerAccount=Number(count||0)>0;document.querySelector("#listingCount").textContent=count||0;document.querySelector("#accountModeTitle").textContent=sellerAccount?"Seller account":"Buyer account";document.querySelector("#accountModeText").textContent=sellerAccount?"Switch to a different email to test buying your own listing.":"This account can buy items listed by other members.";try{const status=await paymentRequest("/.netlify/functions/connect-status");membershipActive=Boolean(status.member);const membershipCard=document.querySelector(".membership-status-card"),membershipButton=document.querySelector("#accountMembershipButton");membershipCard.classList.toggle("active",membershipActive);document.querySelector("#membershipStatus").textContent=membershipActive?"Account active for life":"Required for payouts";membershipButton.hidden=membershipActive;document.querySelector("#payoutStatus").textContent=!membershipActive?"Membership required":status.connected?"Ready to receive payments":status.requirementsStatus==="past_due"?"Action required in Stripe":status.onboardingStatus==="not_started"?"Not connected":"Verification pending";document.querySelector("#connectStripeButton").textContent=!membershipActive?"Become a member":status.connected?"Manage payout setup":status.onboardingStatus==="not_started"?"Connect Stripe":"Continue Stripe setup";window.dispatchEvent(new CustomEvent("flipora:membership-status",{detail:{active:membershipActive}}))}catch{membershipActive=false;document.querySelector("#payoutStatus").textContent="Setup required"}}
db.auth.onAuthStateChange((event,session)=>{updateAccount(session?.user||null);if(event==="PASSWORD_RECOVERY"&&session?.user)showPasswordRecovery()});db.auth.getSession().then(({data})=>{updateAccount(data.session?.user||null);if(passwordRecoveryMode&&data.session?.user)showPasswordRecovery()});
function showToast(message){const toast=document.querySelector("#toast");toast.textContent=message;toast.classList.add("show");window.setTimeout(()=>toast.classList.remove("show"),3000)}
const pageStatus=new URLSearchParams(location.search);if(pageStatus.get("payment")==="success")showToast("Payment completed. Your order is confirmed!");if(pageStatus.get("payment")==="cancelled")showToast("Checkout cancelled. No payment was taken.");if(pageStatus.get("stripe")==="return"){showToast("Stripe onboarding received. Checking your payout status.");history.replaceState({},document.title,location.pathname)}if(pageStatus.get("stripe")==="refresh"){showToast("Your Stripe setup link expired. Opening a fresh one…");const refreshStripeOnboarding=async()=>{if(!currentUser)return window.setTimeout(refreshStripeOnboarding,300);try{const result=await paymentRequest("/.netlify/functions/connect-onboard",{method:"POST"});location.href=result.url}catch(error){history.replaceState({},document.title,location.pathname);showToast(error.message)}};refreshStripeOnboarding()}
if(pageStatus.get("membership")==="success"){showToast("Confirming your lifetime membership…");const confirmPaidMembership=async()=>{if(!currentUser)return window.setTimeout(confirmPaidMembership,300);try{const result=await paymentRequest("/.netlify/functions/confirm-membership",{method:"POST",body:JSON.stringify({sessionId:pageStatus.get("session_id")})});if(result.member){await updateAccount(currentUser);history.replaceState({},document.title,location.pathname);showToast("Your account is active for life. Buyer messages are unlocked.");return}}catch(error){console.error("Membership confirmation failed",error)}window.setTimeout(confirmPaidMembership,2000)};confirmPaidMembership()}if(pageStatus.get("membership")==="cancelled")showToast("Membership checkout cancelled. No payment was taken.");
document.querySelector("#year").textContent=new Date().getFullYear();loadListings();

const membershipCardForCancel=document.querySelector(".membership-status-card");
if(membershipCardForCancel){
  const cancelMembershipButton=document.createElement("button");
  cancelMembershipButton.className="button button-secondary";
  cancelMembershipButton.id="cancelMembershipButton";
  cancelMembershipButton.type="button";
  cancelMembershipButton.textContent="Cancel membership";
  cancelMembershipButton.hidden=true;
  membershipCardForCancel.insertAdjacentElement("afterend",cancelMembershipButton);

  window.addEventListener("flipora:membership-status",event=>{
    cancelMembershipButton.hidden=!Boolean(event.detail?.active);
  });

  cancelMembershipButton.addEventListener("click",async()=>{
    if(!membershipActive)return showToast("There is no active membership to cancel.");
    const confirmed=window.confirm("Cancel your Flipora membership? This will turn off member benefits and seller payout access. Your one-time membership payment is not automatically refunded.");
    if(!confirmed)return;

    cancelMembershipButton.disabled=true;
    cancelMembershipButton.textContent="Cancelling…";
    try{
      const result=await paymentRequest("/.netlify/functions/cancel-membership",{method:"POST",body:"{}"});
      await updateAccount(currentUser);
      showToast(result.message||"Membership cancelled.");
    }catch(error){
      showToast(error.message);
    }finally{
      cancelMembershipButton.disabled=false;
      cancelMembershipButton.textContent="Cancel membership";
    }
  });
}
