-- Stripe Connect additions for Flipora Marketplace
alter table public.profiles add column if not exists stripe_account_id text unique;
alter table public.profiles add column if not exists stripe_onboarding_complete boolean not null default false;
alter table public.profiles add column if not exists membership_active boolean not null default false;
alter table public.profiles add column if not exists membership_paid_at timestamptz;
alter table public.profiles add column if not exists membership_checkout_session_id text;
create unique index if not exists profiles_membership_checkout_session_id_key
  on public.profiles (membership_checkout_session_id)
  where membership_checkout_session_id is not null;

-- Membership and payout fields are controlled only by trusted server functions.
revoke update on table public.profiles from authenticated;
grant update (display_name, city, avatar_url) on public.profiles to authenticated;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id),
  buyer_id uuid not null references public.profiles(id),
  seller_id uuid not null references public.profiles(id),
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text,
  amount_total integer not null check (amount_total >= 0),
  platform_fee integer not null check (platform_fee >= 0),
  currency text not null default 'usd',
  status text not null default 'pending' check (status in ('pending','paid','shipped','delivered','completed','refunded','cancelled','disputed')),
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  refunded_at timestamptz,
  disputed_at timestamptz
);

alter table public.orders add column if not exists refunded_at timestamptz;
alter table public.orders add column if not exists disputed_at timestamptz;
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
  check (status in ('pending','paid','shipped','delivered','completed','refunded','cancelled','disputed'));

alter table public.orders enable row level security;
revoke all on public.orders from anon, authenticated;
grant select on public.orders to authenticated;

drop policy if exists "Buyers and sellers read their orders" on public.orders;
create policy "Buyers and sellers read their orders" on public.orders
  for select to authenticated
  using ((select auth.uid()) = buyer_id or (select auth.uid()) = seller_id);

-- Payment writes are server-only through Netlify functions using the Supabase secret key.

-- Atomically claim a listing for the first completed checkout. This prevents
-- two simultaneous Checkout Sessions from both purchasing the same item.
create or replace function public.complete_flipora_order(
  p_checkout_session_id text,
  p_payment_intent_id text,
  p_paid_time timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  selected_order public.orders%rowtype;
  selected_listing_status text;
begin
  select * into selected_order
  from public.orders
  where stripe_checkout_session_id = p_checkout_session_id
  for update;

  if not found then
    raise exception 'Order not found for checkout session';
  end if;

  if selected_order.status in ('paid','shipped','delivered','completed','disputed') then
    return true;
  end if;

  select status into selected_listing_status
  from public.listings
  where id = selected_order.listing_id
  for update;

  if selected_listing_status <> 'active' then
    update public.orders set status = 'cancelled'
    where id = selected_order.id;
    return false;
  end if;

  update public.orders
  set status = 'paid', stripe_payment_intent_id = p_payment_intent_id, paid_at = p_paid_time
  where id = selected_order.id;

  update public.listings set status = 'sold'
  where id = selected_order.listing_id;

  return true;
end;
$$;

revoke all on function public.complete_flipora_order(text, text, timestamptz) from public, anon, authenticated;
grant execute on function public.complete_flipora_order(text, text, timestamptz) to service_role;

