const sb=window.mscSupabase;let businesses=[],leads=[],portfolioCounts={};
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const date=v=>v?new Date(v).toLocaleString():'—';
const loginShell=document.getElementById('adminLoginShell'),recoveryShell=document.getElementById('recoveryShell'),portal=document.getElementById('adminPortal'),loginMessage=document.getElementById('adminLoginMessage'),logoutButton=document.getElementById('logoutButton');
function setMessage(el,text,type=''){el.textContent=text||'';el.className='form-message'+(type?' '+type:'');}
function cleanAdminUrl(reset=false){const url=new URL(location.href);url.hash='';url.search=reset?'?reset=1':'';return url.toString();}
function showLogin(message='',type=''){portal.hidden=true;recoveryShell.hidden=true;loginShell.hidden=false;logoutButton.hidden=true;setMessage(loginMessage,message,type);}
function showRecovery(){portal.hidden=true;loginShell.hidden=true;recoveryShell.hidden=false;logoutButton.hidden=false;}
async function verifyAdmin(){const{data:userData,error:userError}=await sb.auth.getUser();if(userError||!userData.user){showLogin();return false;}const{data,error}=await sb.rpc('msc_is_admin');if(error||!data){await sb.auth.signOut();showLogin('That signed-in account is not authorized as the administrator.','error');return false;}loginShell.hidden=true;recoveryShell.hidden=true;portal.hidden=false;logoutButton.hidden=false;await loadAll();return true;}
async function loadAll(){const[b,l,p]=await Promise.all([sb.from('msc_business_profiles').select('*').order('created_at',{ascending:false}),sb.from('msc_customer_requests').select('*').order('created_at',{ascending:false}),sb.from('msc_work_photos').select('id,business_id')]);const err=b.error||l.error||p.error;if(err){const m=document.getElementById('accessMessage');m.hidden=false;m.textContent=err.message;return;}document.getElementById('accessMessage').hidden=true;businesses=b.data||[];leads=l.data||[];portfolioCounts={};(p.data||[]).forEach(x=>portfolioCounts[x.business_id]=(portfolioCounts[x.business_id]||0)+1);renderStats();renderBusinesses();renderLeads();}
function renderStats(){document.getElementById('statNew').textContent=leads.filter(x=>x.status==='new').length;document.getElementById('statAssigned').textContent=leads.filter(x=>x.assigned_business_id).length;document.getElementById('statPending').textContent=businesses.filter(x=>x.status==='pending').length;document.getElementById('statApproved').textContent=businesses.filter(x=>x.status==='approved').length;}
function businessOptions(selected){return'<option value="">Unassigned</option>'+businesses.filter(b=>b.status==='approved'||b.id===selected).map(b=>`<option value="${b.id}" ${b.id===selected?'selected':''}>${esc(b.business_name)} — ${esc(b.service_category)}</option>`).join('');}
function renderLeads(){const root=document.getElementById('adminLeadList');if(!leads.length){root.innerHTML='<div class="empty-state">No customer requests yet.</div>';return;}root.innerHTML=leads.map(j=>`<article class="admin-card"><div class="admin-card-top"><div><span class="eyebrow">${esc(j.service_category)}</span><h3>${esc(j.customer_name)}</h3><p>${esc(j.customer_phone)} • ${esc(j.customer_email)}</p></div><span class="job-status">${esc(j.status)}</span></div><div class="admin-job-details"><p><strong>Address:</strong> ${esc(j.street_address)}, ${esc(j.city)}, GA ${esc(j.zip)}</p><p><strong>Requested:</strong> ${j.preferred_date?esc(j.preferred_date):'Flexible'} ${j.preferred_time?('• '+esc(j.preferred_time)):''}</p><p><strong>Job:</strong> ${esc(j.job_description)}</p>${j.access_notes?`<p><strong>Notes:</strong> ${esc(j.access_notes)}</p>`:''}<small>Submitted ${esc(date(j.created_at))}</small></div><div class="admin-controls"><label>Assign business<select id="assign-${j.id}">${businessOptions(j.assigned_business_id)}</select></label><label>Job status<select id="status-${j.id}"><option ${j.status==='new'?'selected':''}>new</option><option ${j.status==='assigned'?'selected':''}>assigned</option><option ${j.status==='accepted'?'selected':''}>accepted</option><option ${j.status==='in_progress'?'selected':''}>in_progress</option><option ${j.status==='completed'?'selected':''}>completed</option><option ${j.status==='closed'?'selected':''}>closed</option></select></label><button class="btn btn-small" onclick="saveLead('${j.id}')">Save assignment</button></div></article>`).join('');}
function renderBusinesses(){const root=document.getElementById('businessList');if(!businesses.length){root.innerHTML='<div class="empty-state">No business accounts yet.</div>';return;}root.innerHTML=businesses.map(b=>`<article class="admin-card"><div class="admin-card-top"><div><span class="eyebrow">${esc(b.service_category)}</span><h3>${esc(b.business_name)}</h3><p>${esc(b.owner_name)} • ${esc(b.phone)} • ${esc(b.service_area)}</p></div><span class="status-pill status-${esc(b.status)}">${esc(b.status).toUpperCase()}</span></div><p>${esc(b.description||'No description provided.')}</p><p class="portfolio-count"><strong>Work gallery:</strong> ${portfolioCounts[b.id]||0} photo${(portfolioCounts[b.id]||0)===1?'':'s'}</p><div class="admin-controls"><label>Provider status<select id="bizstatus-${b.id}"><option ${b.status==='pending'?'selected':''}>pending</option><option ${b.status==='approved'?'selected':''}>approved</option><option ${b.status==='suspended'?'selected':''}>suspended</option></select></label><label>Plan<select id="bizplan-${b.id}"><option ${b.plan==='Starter'?'selected':''}>Starter</option><option ${b.plan==='Featured'?'selected':''}>Featured</option></select></label><button class="btn btn-small" onclick="saveBusiness('${b.id}')">Save business</button></div></article>`).join('');}
window.saveLead=async id=>{const assigned=document.getElementById('assign-'+id).value||null;let status=document.getElementById('status-'+id).value;if(assigned&&status==='new')status='assigned';if(!assigned&&status==='assigned')status='new';const{error}=await sb.from('msc_customer_requests').update({assigned_business_id:assigned,status,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else loadAll();};
window.saveBusiness=async id=>{const status=document.getElementById('bizstatus-'+id).value,plan=document.getElementById('bizplan-'+id).value;const{error}=await sb.from('msc_business_profiles').update({status,plan,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else loadAll();};
document.getElementById('adminPasswordForm').addEventListener('submit',async e=>{e.preventDefault();const email=document.getElementById('adminEmail').value.trim(),password=document.getElementById('adminPassword').value;setMessage(loginMessage,'Signing in…');const{error}=await sb.auth.signInWithPassword({email,password});if(error){setMessage(loginMessage,'Password login failed. Use the secure email-link option or reset your password below.','error');return;}await verifyAdmin();});
document.getElementById('magicLinkForm').addEventListener('submit',async e=>{e.preventDefault();const email=document.getElementById('magicEmail').value.trim();setMessage(loginMessage,'Sending secure sign-in link…');const{error}=await sb.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:cleanAdminUrl(false)}});if(error){setMessage(loginMessage,error.message,'error');return;}setMessage(loginMessage,'Secure sign-in link sent. Open the email and tap the link to enter administration.','success');});
document.getElementById('resetPasswordButton').addEventListener('click',async()=>{const email=(document.getElementById('adminEmail').value||document.getElementById('magicEmail').value).trim();if(!email){setMessage(loginMessage,'Enter the administrator email first, then tap reset password.','error');return;}setMessage(loginMessage,'Sending password recovery email…');const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:cleanAdminUrl(true)});if(error){setMessage(loginMessage,error.message,'error');return;}setMessage(loginMessage,'Password recovery email sent. Open it and return here to choose a new password.','success');});
document.getElementById('recoveryForm').addEventListener('submit',async e=>{e.preventDefault();const password=document.getElementById('newPassword').value,confirm=document.getElementById('confirmPassword').value,message=document.getElementById('recoveryMessage');if(password!==confirm){setMessage(message,'The passwords do not match.','error');return;}setMessage(message,'Saving new password…');const{error}=await sb.auth.updateUser({password});if(error){setMessage(message,error.message,'error');return;}setMessage(message,'Password updated. Opening administration…','success');history.replaceState({},'',cleanAdminUrl(false));setTimeout(verifyAdmin,200);});
document.getElementById('refreshButton').onclick=loadAll;logoutButton.onclick=async()=>{await sb.auth.signOut();history.replaceState({},'',cleanAdminUrl(false));showLogin('Signed out.');};
sb.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')setTimeout(showRecovery,0);else if(event==='SIGNED_IN'&&session)setTimeout(verifyAdmin,0);});
(async()=>{if(new URLSearchParams(location.search).get('reset')==='1'){const{data:{session}}=await sb.auth.getSession();if(session){showRecovery();return;}}await verifyAdmin();})();
